site_name: "rthor"
site_description: "Documentation website for rthor"
site_author: "Andrew Mitchell"
site_url: https://drandrewmitchell.com/rthor/
copyright: Copyright &copy; 2025 Andrew Mitchell
repo_url: "https://github.com/MitchellAcoustics/rthor/"
repo_name: "MitchellAcoustics/rthor"
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.path # waiting for general release
    - navigation.indexes
    - navigation.instant
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Installation: user-guide/installation.md
  - Examples:
      - Basic Usage: examples/basic-usage.py
      - Advanced Features: examples/advanced-features.py
      - Paper Validation: examples/paper-validation.py
  - Core Concepts: user-guide/concepts.md
  - API Reference:
      - Overview: api/overview.md
      - Core Functions: api/api.md
      - Result Classes: api/result-classes.md
      - Reference:
          - api/reference/index.md
          - _input: api/reference/input.md
          - _permutations: api/reference/permutations.md
          - _core: api/reference/core.md
          - _validation: api/reference/validation.md
          - _vectorized: api/reference/vectorized.md
          - I/O Functions: api/reference/io.md
  - License: LICENSE.md

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets

plugins:
  - search
  - autorefs
  - bibtex:
      bib_file: docs/refs.bib
      enable_inline_citations: false
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocs-jupyter:
      execute: true
      include_source: true
      allow_errors: false
      theme: default
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
          options:
            docstring_style: google
            docstring_section_style: spacy
            members_order: source
            merge_init_into_class: true
            modernize_annotations: true
            overloads_only: true
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
            show_overloads: true
            show_submodules: true
            show_root_heading: true
            summary: true
          paths: [src]
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  # - api-autonav:
  #     modules: ["src/rthor"]
  #     module_options:
  #       ".*":
  #         merge_init_into_class: true
  #         show_symbol_type_heading: true # waiting for general release
  #         show_symbol_type_toc: true
  #     exclude: ["re: ^soundscapy$"] # ends up double-documenting top level imports, so don't auto generate things exported from rthor.__init__.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/MitchellAcoustics"
  # version:
  #   provider: mike

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
