site_name: "pythor"
site_description: "Documentation website for pythor"
site_author: "Andrew Mitchell"
copyright: Copyright &copy; 2025 Andrew Mitchell
repo_url: "https://github.com/MitchellAcoustics/pythor/"
repo_name: "MitchellAcoustics/pythor"
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Getting Started:
      - Installation: user-guide/installation.md
      - Quick Start: user-guide/quickstart.md
  - Examples:
      - Basic Usage: examples/basic-usage.py
      - Advanced Features: examples/advanced-features.py
  - User Guide:
      - Core Concepts: user-guide/concepts.md
      - Input Formats: user-guide/input-formats.md
      - Interpreting Results: user-guide/results.md
  - API Reference: api.md
  - License: LICENSE.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: true
      include_source: true
      allow_errors: false
      theme: default
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
          options:
            docstring_style: google
            docstring_section_style: spacy
            separate_signature: true
            merge_init_into_class: true
            show_symbol_type_heading: true # waiting for general release
            show_symbol_type_toc: true
            modernize_annotations: true
            summary: true
            show_submodules: true
          paths: [src]
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - api-autonav:
      modules: ["src/pythor"]
      module_options:
        ".*":
          merge_init_into_class: true
          show_symbol_type_heading: true # waiting for general release
          show_symbol_type_toc: true
      exclude: ["re: ^soundscapy$"] # ends up double-documenting top level imports, so don't auto generate things exported from pythor.__init__.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/MitchellAcoustics"

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
