site_name: "pythor"
site_description: "Documentation website for pythor"
site_author: "Andrew Mitchell"
copyright: "Copyright © 2025 Andrew Mitchell"
repo_url: "https://github.com/MitchellAcoustics/pythor/"
repo_name: "MitchellAcoustics/pythor"
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  features:
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Getting Started:
      - Installation: user-guide/installation.md
      - Quick Start: user-guide/quickstart.md
  - Examples:
      - Basic Usage: examples/basic-usage.md
      - Advanced Features: examples/advanced-features.md
  - User Guide:
      - Core Concepts: user-guide/concepts.md
      - Input Formats: user-guide/input-formats.md
      - Interpreting Results: user-guide/results.md
  - API Reference: api.md
  - License: LICENSE.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.blocks.html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details

plugins:
  - search
  - marimo
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
          options:
            docstring_style: google
            show_submodules: true
          paths: [src]
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/MitchellAcoustics"
