;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<AppWindow>>>;;;
[AppWindow]
DpiWindowSizeFactor=1
WindowPosition=3,75
WindowSize=1794,1091
;;;<<<ImGui_655921752_Default>>>;;;
[Window][Image Inspector]
Pos=0,19
Size=1794,1046
Collapsed=0
DockId=0x00000001,1

[Window][Log]
Pos=0,803
Size=1794,262
Collapsed=0
DockId=0x00000002,0

[Window][Functions Graph]
Pos=0,19
Size=1794,1046
Collapsed=0
DockId=0x00000001,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][StatusBar]
Pos=0,1064
Size=1794,32
Collapsed=0

[Window][Confirm Raise exception##raise_exception4938925312]
Pos=686,546
Size=347,197
Collapsed=0

[Table][0x8D18FE8B,7]
RefScale=15
Column 0  Width=53
Column 1  Width=82
Column 2  Width=84
Column 3  Width=35
Column 4  Width=123
Column 5  Width=137
Column 6  Width=43

[Table][0xE2118BC8,7]
RefScale=15

[Table][0x88850947,7]
RefScale=15

[Table][0x52F904EC,7]
RefScale=15

[Docking][Data]
DockSpace   ID=0xAFC85805 Window=0x079D3A04 Pos=3,94 Size=1794,1046 Split=Y
  DockNode  ID=0x00000001 Parent=0xAFC85805 SizeRef=1600,686 CentralNode=1 Selected=0x8EACBB62
  DockNode  ID=0x00000002 Parent=0xAFC85805 SizeRef=1600,262 Selected=0x139FDA3F

;;;<<<Layout_655921752_Default>>>;;;
[Visibility]
1328366607_Functions_Graph=true
3117503904_Image_Inspector=false
3546767630_Log=false
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=true
[Theme]
Name=BlackIsBlack
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"MainDockSpace":2949142533,"log_dock":2}}
